server:
  port: 8081

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:

        # =========================
        # PUBLIC AUTH APIs (NO JWT)
        # =========================
        - id: auth-public
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/register,/auth/login,/auth/refresh

        # =========================
        # PROTECTED AUTH APIs (JWT)
        # =========================
        - id: auth-protected
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/change-password
          filters:
            - JwtAuthFilter

        # =========================
        # USER SERVICE (JWT)
        # =========================
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
          filters:
            - JwtAuthFilter

        # =========================
        # TRANSACTION SERVICE (JWT)
        # =========================
        - id: transaction-service
          uri: lb://TRANSACTION-SERVICE
          predicates:
            - Path=/transactions/**
          filters:
            - JwtAuthFilter

# =========================
# EUREKA CONFIG
# =========================
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

# =========================
# ACTUATOR
# =========================
management:
  endpoints:
    web:
      exposure:
        include: health,info

# =========================
# LOGGING (DEBUG GATEWAY)
# =========================
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
