server:
  port: 8081

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
         # PUBLIC AUTH APIs
        - id: auth-public
          uri: lb://AUTH-SERVICE
          predicates:
             - Path=/auth/register
             - Path=/auth/login
             - Path=/auth/refresh

        # PROTECTED AUTH APIs
        - id: auth-protected
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/change-password
          filters:
            - JwtAuthFilter

        # PROTECTED SERVICES (JWT REQUIRED)
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
          filters:
            - JwtAuthFilter

        - id: transaction-service
          uri: lb://TRANSACTION-SERVICE
          predicates:
            - Path=/transactions/**
          filters:
            - JwtAuthFilter

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info

