server:
  port: 8081

spring:
  application:
    name: api-gateway

  cloud:
    gateway:

      # 1️⃣ Explicit routes (primary)
      server:
        webmvc:
          routes:
            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/auth/**

      


