server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/transaction_service
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
